// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: proto/kvholder.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KVCacheHolderClient is the client API for KVCacheHolder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KVCacheHolderClient interface {
	// 查询
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error)
	// 插入/更新
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddReply, error)
}

type kVCacheHolderClient struct {
	cc grpc.ClientConnInterface
}

func NewKVCacheHolderClient(cc grpc.ClientConnInterface) KVCacheHolderClient {
	return &kVCacheHolderClient{cc}
}

func (c *kVCacheHolderClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error) {
	out := new(GetReply)
	err := c.cc.Invoke(ctx, "/KVCacheHolder/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVCacheHolderClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddReply, error) {
	out := new(AddReply)
	err := c.cc.Invoke(ctx, "/KVCacheHolder/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KVCacheHolderServer is the server API for KVCacheHolder service.
// All implementations must embed UnimplementedKVCacheHolderServer
// for forward compatibility
type KVCacheHolderServer interface {
	// 查询
	Get(context.Context, *GetRequest) (*GetReply, error)
	// 插入/更新
	Add(context.Context, *AddRequest) (*AddReply, error)
	mustEmbedUnimplementedKVCacheHolderServer()
}

// UnimplementedKVCacheHolderServer must be embedded to have forward compatible implementations.
type UnimplementedKVCacheHolderServer struct {
}

func (UnimplementedKVCacheHolderServer) Get(context.Context, *GetRequest) (*GetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedKVCacheHolderServer) Add(context.Context, *AddRequest) (*AddReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedKVCacheHolderServer) mustEmbedUnimplementedKVCacheHolderServer() {}

// UnsafeKVCacheHolderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KVCacheHolderServer will
// result in compilation errors.
type UnsafeKVCacheHolderServer interface {
	mustEmbedUnimplementedKVCacheHolderServer()
}

func RegisterKVCacheHolderServer(s grpc.ServiceRegistrar, srv KVCacheHolderServer) {
	s.RegisterService(&KVCacheHolder_ServiceDesc, srv)
}

func _KVCacheHolder_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVCacheHolderServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KVCacheHolder/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVCacheHolderServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVCacheHolder_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVCacheHolderServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KVCacheHolder/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVCacheHolderServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KVCacheHolder_ServiceDesc is the grpc.ServiceDesc for KVCacheHolder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KVCacheHolder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "KVCacheHolder",
	HandlerType: (*KVCacheHolderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _KVCacheHolder_Get_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _KVCacheHolder_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/kvholder.proto",
}
